### ISSUE TITLE
Feedback Paleta de colores

### ISSUE THREAD

**Issue by nadiatapm** [AriellaRogueN/AriellaRodriguezN#1]
Ari tu paleta de colores es demasiado monocromática, te aconsejo buscar otro color que haga contraste con el morado  por ejemplo: blanco, rosado.
En cuanto al diseño de tu portafolio , te felicito porque tienes una idea clara de lo que quieres mostrar.

**Comment by AriellaRogueN** [comment]
ok!! gracias
